### ISSUE TITLE
has no access in the google drive

### ISSUE THREAD

**Issue by iefengjian** [sangrockEG/ACR#4]
please open access of the google drive, now, I need request the access.

**Comment by iefengjian** [comment]
the weight file of the rep "AEFT" is also unsuitable.

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Traceback (most recent call last):
  File "train_pl.py", line 97, in <module>
    model = getattr(importlib.import_module('models.exp_'+args.exp), 'Exp')(args)
  File "/media/data/512G/fj/ACR/models/exp_recon_cvpr23.py", line 50, in __init__
    self.build_framework(args.phase)
  File "/media/data/512G/fj/ACR/models/exp_recon_cvpr23.py", line 59, in build_framework
    self.net_recon.load_state_dict(resnet38d.convert_mxnet_to_torch('./pretrained/resnet_38d.params'), strict=False)
  File "/media/data/512G/fj/ACR/networks/resnet38d.py", line 127, in convert_mxnet_to_torch
    save_dict = mxnet.nd.load(filename)
  File "/media/data/512G/fj/conda_env/wsds/lib/python3.8/site-packages/mxnet/ndarray/utils.py", line 171, in load
    check_call(_LIB.MXNDArrayLoad(c_str(fname),
  File "/media/data/512G/fj/conda_env/wsds/lib/python3.8/site-packages/mxnet/base.py", line 246, in check_call
    raise get_last_ffi_error()
mxnet.base.MXNetError: Traceback (most recent call last):
  File "../src/ndarray/ndarray.cc", line 1861
MXNetError: Check failed: fi->Read(data): Invalid NDArray file format
